apiVersion: iam.aws.m.upbound.io/v1beta1
kind: Role
metadata:
  name: relcoord-ecr-publish
  annotations:
    crossplane.io/external-name: relcoord-ecr-publish
spec:
  forProvider:
    path: /product-roles/
    permissionsBoundary: arn:aws:iam::{{account_id}}:policy/pipeline-policies/crossplane-approle-permissions-boundary
    assumeRolePolicy: |
      {
        "Version": "2012-10-17",
        "Statement": [
          {
            "Effect": "Allow",
            "Principal": {
              "Federated": "arn:aws:iam::{{account_id}}:oidc-provider/token.actions.githubusercontent.com"
            },
            "Action": "sts:AssumeRoleWithWebIdentity",
            "Condition": {
              "StringEquals": {
                "token.actions.githubusercontent.com:aud": "sts.amazonaws.com"
              },
              "StringLike": {
                "token.actions.githubusercontent.com:sub": [
                  "repo:portswigger-cloud/relcoord:ref:refs/heads/main"
                ]
              }
            }
          }
        ]
      }
