apiVersion: iam.aws.m.upbound.io/v1beta1
kind: RolePolicy
metadata:
  name: relcoord-ecr-publish
  annotations:
    crossplane.io/external-name: relcoord-ecr-publish
spec:
  forProvider:
    role: relcoord-ecr-publish
    policy: |
      {
        "Version": "2012-10-17",
        "Statement": [
          {
            "Effect": "Allow",
            "Action": [
              "ecr-public:DescribeImageTags",
              "ecr-public:DescribeImages",
              "ecr-public:UploadLayerPart",
              "ecr-public:DeleteRepositoryPolicy",
              "ecr-public:DescribeRegistries",
              "ecr-public:GetRepositoryCatalogData",
              "ecr-public:CompleteLayerUpload",
              "ecr-public:GetRepositoryPolicy",
              "ecr-public:InitiateLayerUpload",
              "ecr-public:DescribeRepositories",
              "ecr-public:PutImage",
              "ecr-public:GetRegistryCatalogData",
              "ecr-public:ListTagsForResource",
              "ecr-public:BatchCheckLayerAvailability"
            ],
            "Resource": [
              "arn:aws:ecr-public::{{account_id}}:repository/relcoord",
              "arn:aws:ecr-public::{{account_id}}:registry/*"
            ]
          },
          {
            "Effect": "Allow",
            "Action": "ecr-public:GetAuthorizationToken",
            "Resource": "*"
          },
          {
            "Effect": "Allow",
            "Action": "sts:GetServiceBearerToken",
            "Resource": "*"
          }
        ]
      }
