apiVersion: dynamodb.aws.m.upbound.io/v1beta1
kind: Table
metadata:
  name: platform-relcoord
  annotations:
    crossplane.io/external-name: platform-relcoord
spec:
  forProvider:
    region: eu-west-1
    billingMode: PAY_PER_REQUEST
    hashKey: pk
    rangeKey: sk
    attribute:
    - name: pk
      type: S
    - name: sk
      type: S
