# SPDX-License-Identifier: MIT
# SPDX-FileCopyrightText: 2026 PortSwigger Ltd
"""Validate a generated manifest tree with manifest-validator.

relcoord holds a URL and a list of opaque check names, and nothing else: which
tools run, their versions, the rulesets and the pass/fail decision all belong to
manifest-validator, because relcoord's own config is generated by the pipeline
being validated. A verdict is read here, never recomputed from its findings.

The content digest is a wire contract shared with that service, described in its
README under "Content digest" and implemented in its ``trees.compute_digest``.
The two implementations have to agree byte for byte, so a fixed tree hashes to a
fixed digest in the tests of both.
"""

from __future__ import annotations

import gzip
import hashlib
import io
import json
import logging
import tarfile
from collections.abc import Callable, Iterator, Mapping, Sequence
from dataclasses import dataclass
from pathlib import Path
from typing import Any, Protocol

import httpx

logger = logging.getLogger(__name__)

DIGEST_PREFIX = b"manifest-validator-tree-v1\x00"
SSE_MEDIA_TYPE = "text/event-stream"
TREE_MEDIA_TYPE = "application/gzip"
VALIDATE_PATH = "/v1/validate"
# A cold kics scan of a large tree is the slow case here, and the validator has
# no queue to hand the work to: the request is the scan.
DEFAULT_TIMEOUT_SECONDS = 900.0
# Directories a generated output never means to hand to a scanner. The manifests
# checkout is a git repository, and the output directory can be its root.
EXCLUDED_DIRECTORIES = frozenset({".git"})


class ValidationError(Exception):
    """Raised when a validation did not produce a verdict.

    A transport failure, an error response, an ``error`` event or a stream that
    ends without a result all land here, and all of them mean the tree was not
    validated. Nothing may read that as a pass.
    """


@dataclass(frozen=True)
class Finding:
    rule_id: str
    severity: str
    message: str
    file: str | None = None
    resource: str | None = None
    similarity_id: str | None = None
    accepted: str | None = None
    """Why this finding does not fail the verdict, or None if it does."""

    @property
    def fails(self) -> bool:
        return self.accepted is None


@dataclass(frozen=True)
class Verdict:
    """One check's opinion of one tree, as manifest-validator reported it."""

    passed: bool
    tool: str
    tool_version: str = ""
    ruleset_digest: str = ""
    findings: tuple[Finding, ...] = ()
    advisory: bool = False
    """Whether the validator reports this check without gating on it.

    ``passed`` is already true for an advisory check, so nothing here changes
    what relcoord pushes. It matters only for what a comment says: findings that
    stopped nothing have to read that way, or a reviewer assumes their merge is
    blocked.
    """

    @property
    def failing_findings(self) -> tuple[Finding, ...]:
        """Findings that fail the verdict, which an advisory check has none of."""
        if self.advisory:
            return ()
        return tuple(finding for finding in self.findings if finding.fails)

    @property
    def advisory_findings(self) -> tuple[Finding, ...]:
        if not self.advisory:
            return ()
        return tuple(finding for finding in self.findings if finding.fails)


@dataclass(frozen=True)
class Validation:
    """Every check's verdict on one output's tree."""

    passed: bool
    digest: str
    cached: bool = False
    verdicts: tuple[Verdict, ...] = ()

    @property
    def failed_verdicts(self) -> tuple[Verdict, ...]:
        return tuple(verdict for verdict in self.verdicts if not verdict.passed)

    @property
    def failing_findings(self) -> tuple[Finding, ...]:
        return tuple(
            finding for verdict in self.verdicts for finding in verdict.failing_findings
        )

    @property
    def advisory_findings(self) -> tuple[Finding, ...]:
        return tuple(
            finding
            for verdict in self.verdicts
            for finding in verdict.advisory_findings
        )

    @property
    def accepted_count(self) -> int:
        return sum(
            1
            for verdict in self.verdicts
            for finding in verdict.findings
            if not finding.fails
        )


ValidationProgress = Callable[[str, str], None]
"""Sink for a validator phase and its message, as manifest-validator names them."""


def ignore_validation_progress(phase: str, message: str) -> None:
    """Discard validator progress, for callers that do not observe it."""


class TreeValidator(Protocol):
    def validate(
        self,
        files: Mapping[str, bytes],
        checks: Sequence[str] = (),
        *,
        progress: ValidationProgress = ignore_validation_progress,
    ) -> Validation: ...


def compute_digest(files: Mapping[str, bytes]) -> str:
    """Digest a tree's content the way manifest-validator does.

    The lengths are framing rather than decoration: without them ``{"ab": "c"}``
    and ``{"a": "bc"}`` would hash the same bytes. Changing any of this
    invalidates every cached verdict, so it moves to a ``-v2`` prefix rather
    than being edited.
    """
    digest = hashlib.sha256()
    digest.update(DIGEST_PREFIX)
    for path in sorted(files):
        content = files[path]
        encoded_path = path.encode("utf-8")
        digest.update(len(encoded_path).to_bytes(8, "big"))
        digest.update(encoded_path)
        digest.update(len(content).to_bytes(8, "big"))
        digest.update(content)
    return f"sha256:{digest.hexdigest()}"


def read_tree(root: Path) -> dict[str, bytes]:
    """Read a generated output directory as the tree to validate."""
    files: dict[str, bytes] = {}
    for path in sorted(root.rglob("*")):
        if not path.is_file() or path.is_symlink():
            continue
        relative = path.relative_to(root)
        if EXCLUDED_DIRECTORIES.intersection(relative.parts):
            continue
        files[relative.as_posix()] = path.read_bytes()
    return files


def tar_gz(files: Mapping[str, bytes]) -> bytes:
    """Pack a tree as the gzipped tar ``POST /v1/validate`` takes as its body."""
    buffer = io.BytesIO()
    # mtime=0 so that the same tree packs to the same bytes; the verdict is keyed
    # on the content digest, but a stable blob keeps a retry comparable.
    with (
        gzip.GzipFile(fileobj=buffer, mode="wb", mtime=0) as compressed,
        tarfile.open(fileobj=compressed, mode="w") as archive,
    ):
        for path in sorted(files):
            content = files[path]
            info = tarfile.TarInfo(name=path)
            info.size = len(content)
            info.mtime = 0
            archive.addfile(info, io.BytesIO(content))
    return buffer.getvalue()


@dataclass(frozen=True)
class HttpTreeValidator:
    """Validate a tree over manifest-validator's HTTP API.

    The request always asks for the event stream, so a long scan reports what it
    is doing rather than holding one connection silent for minutes, and the
    phases the validator names travel straight into relcoord's own stream. The
    verdict is the ``result`` event; anything else finishing the stream is a
    failure.
    """

    url: str
    timeout_seconds: float = DEFAULT_TIMEOUT_SECONDS
    client: httpx.Client | None = None
    """Client to use in place of a request-scoped one, for tests."""

    def validate(
        self,
        files: Mapping[str, bytes],
        checks: Sequence[str] = (),
        *,
        progress: ValidationProgress = ignore_validation_progress,
    ) -> Validation:
        digest = compute_digest(files)
        params = [("digest", digest), *(("check", check) for check in checks)]
        endpoint = f"{self.url.rstrip('/')}{VALIDATE_PATH}"
        body = tar_gz(files)
        logger.info(
            "validating %d file(s) as %s with checks %s at %s",
            len(files),
            digest,
            ", ".join(checks) if checks else "<validator defaults>",
            endpoint,
        )
        if self.client is not None:
            return self._validate_with(self.client, endpoint, params, body, progress)
        with httpx.Client(timeout=self.timeout_seconds) as client:
            return self._validate_with(client, endpoint, params, body, progress)

    def _validate_with(
        self,
        client: httpx.Client,
        endpoint: str,
        params: Sequence[tuple[str, str]],
        body: bytes,
        progress: ValidationProgress,
    ) -> Validation:
        try:
            with client.stream(
                "POST",
                endpoint,
                params=list(params),
                content=body,
                headers={"content-type": TREE_MEDIA_TYPE, "accept": SSE_MEDIA_TYPE},
                timeout=self.timeout_seconds,
            ) as response:
                if response.status_code != httpx.codes.OK:
                    raise ValidationError(
                        _error_response_message(endpoint, response)
                    ) from None
                return _read_validation(response.iter_lines(), progress)
        except httpx.HTTPError as exc:
            raise ValidationError(
                f"failed to reach manifest-validator at {endpoint}: {exc}"
            ) from exc


def _error_response_message(endpoint: str, response: httpx.Response) -> str:
    detail = response.read().decode(errors="replace").strip()
    try:
        parsed = json.loads(detail)
    except ValueError:
        parsed = None
    if isinstance(parsed, dict) and isinstance(parsed.get("error"), str):
        detail = parsed["error"]
    return (
        f"manifest-validator at {endpoint} answered {response.status_code}"
        f"{f': {detail}' if detail else ''}"
    )


def _read_validation(lines: Iterator[str], progress: ValidationProgress) -> Validation:
    """Turn the validator's event stream into a verdict, reporting as it goes."""
    event: str | None = None
    data: str | None = None
    for line in lines:
        stripped = line.rstrip("\r")
        if stripped.startswith("event:"):
            event = stripped[len("event:") :].strip()
            continue
        if stripped.startswith("data:"):
            data = stripped[len("data:") :].strip()
            continue
        if stripped:
            continue
        result = _handle_event(event, data, progress)
        event = data = None
        if result is not None:
            return result
    result = _handle_event(event, data, progress)
    if result is not None:
        return result
    raise ValidationError("manifest-validator ended the event stream without a verdict")


def _handle_event(
    event: str | None, data: str | None, progress: ValidationProgress
) -> Validation | None:
    if event is None:
        return None
    payload = _event_payload(data)
    if event == "result":
        return _validation_from_payload(payload)
    if event == "error":
        raise ValidationError(
            f"manifest-validator reported an error: {_message(payload)}"
        )
    progress(event, _message(payload))
    return None


def _event_payload(data: str | None) -> dict[str, Any]:
    if not data:
        return {}
    try:
        parsed = json.loads(data)
    except ValueError as exc:
        raise ValidationError(
            f"manifest-validator sent an event relcoord could not read: {exc}"
        ) from exc
    return parsed if isinstance(parsed, dict) else {}


def _message(payload: Mapping[str, Any]) -> str:
    message = payload.get("message")
    return message if isinstance(message, str) else ""


def _validation_from_payload(payload: Mapping[str, Any]) -> Validation:
    passed = payload.get("passed")
    digest = payload.get("digest")
    if not isinstance(passed, bool) or not isinstance(digest, str):
        raise ValidationError(
            "manifest-validator sent a verdict without a passed flag and a digest"
        )
    raw_verdicts = payload.get("verdicts")
    verdicts = raw_verdicts if isinstance(raw_verdicts, list) else []
    return Validation(
        passed=passed,
        digest=digest,
        cached=bool(payload.get("cached")),
        verdicts=tuple(
            _verdict_from_payload(entry)
            for entry in verdicts
            if isinstance(entry, dict)
        ),
    )


def _verdict_from_payload(payload: Mapping[str, Any]) -> Verdict:
    raw_findings = payload.get("findings")
    findings = raw_findings if isinstance(raw_findings, list) else []
    return Verdict(
        passed=bool(payload.get("passed")),
        advisory=bool(payload.get("advisory")),
        tool=_string(payload, "tool"),
        tool_version=_string(payload, "tool_version"),
        ruleset_digest=_string(payload, "ruleset_digest"),
        findings=tuple(
            _finding_from_payload(entry)
            for entry in findings
            if isinstance(entry, dict)
        ),
    )


def _finding_from_payload(payload: Mapping[str, Any]) -> Finding:
    return Finding(
        rule_id=_string(payload, "rule_id"),
        severity=_string(payload, "severity"),
        message=_string(payload, "message"),
        file=_optional_string(payload, "file"),
        resource=_optional_string(payload, "resource"),
        similarity_id=_optional_string(payload, "similarity_id"),
        accepted=_optional_string(payload, "accepted"),
    )


def _string(payload: Mapping[str, Any], key: str) -> str:
    value = payload.get(key)
    return value if isinstance(value, str) else ""


def _optional_string(payload: Mapping[str, Any], key: str) -> str | None:
    value = payload.get(key)
    return value if isinstance(value, str) else None


@dataclass(frozen=True)
class OutputValidation:
    """What validating one configured output came to.

    ``error`` carries the reason there is no ``validation``, which only a diff
    reports: a change that cannot get a verdict fails rather than pushing.
    Neither means there was nothing to validate.
    """

    output: str
    checks: tuple[str, ...] = ()
    validation: Validation | None = None
    error: str | None = None

    @property
    def failed(self) -> bool:
        """Whether this output must not be pushed."""
        if self.error is not None:
            return True
        return self.validation is not None and not self.validation.passed
